Complete random password for node VMs

diff --git a/lib/chef/knife/bootstrap/centos5-vmware.erb b/lib/chef/knife/bootstrap/centos5-vmware.erb
--- a/lib/chef/knife/bootstrap/centos5-vmware.erb
+++ b/lib/chef/knife/bootstrap/centos5-vmware.erb
@@ -79,6 +79,123 @@ EOP
 <%- end %>
 fi
 
+<%- unless knife_config[:vm_use_default_password] %>
+# Generate random password for VMs
+<% usr_sbin_path = "/usr/sbin" %>
+(
+cat <<'EOP'
+#!/usr/bin/python
+
+import crypt, string, random, sys
+
+salt_chars = string.ascii_letters + string.digits + "./"
+salt = "".join([random.choice(salt_chars) for x in range(16)])
+
+password = sys.stdin.readline().strip("\n")
+
+encpw = crypt.crypt(password, "\$6\$%s\$" % salt)
+
+sys.stdout.write(encpw + "\n")
+EOP
+) > <%= usr_sbin_path %>/password-crypt
+chmod 775 <%= usr_sbin_path %>/password-crypt
+
+(
+cat <<'EOP'
+#!/bin/bash
+
+# With argument -a, this sets a random password and sets it up to be
+# displayed on the login screen
+# With a argument -u, the user is prompted for the password and the password
+# which is set is not displayed on the screen.
+
+LOGIN_MSG=<%= usr_sbin_path %>/login_msg
+chmod 644 \$LOGIN_MSG
+
+if [ \`id -u\` != 0 ]; then
+  echo "Permission denied: run this script with root user"
+  exit 1
+fi
+
+if [ "\$1" == "-u" ]; then
+   # User set password
+   read -p "New password: " -s p1 && echo && \\
+   read -p "Retype password: " -s p2 && echo
+   if [ \$? != 0 ]; then
+      echo Not changing password
+      exit 1
+   fi
+   if [ "\$p1" != "\$p2" ]; then
+      echo Passwords do not match
+      exit 1
+   fi
+   passwd="\$p1"
+   display_passwd="Password set by user"
+   notification=""
+elif [ "\$1" == "-a" ]; then
+   # Auto generated password
+   passwd=\`openssl rand -base64 6\`
+   if [ \$? != 0 ]; then
+      echo "Error generating random password"
+      exit 1
+   fi
+   display_passwd="\$passwd"
+   notification="You can change password after login using script sudo <%= usr_sbin_path %>/serengeti-password -u"
+else
+   echo "Usage:" "\$0" "[ -a | -u ]"
+   echo "   -a, set password using auto generated password"
+   echo "   -u, user reset password"
+   exit 1
+fi
+
+cryptpasswd=\`echo \$passwd | <%= usr_sbin_path %>/password-crypt\` && \\
+rm -f \$LOGIN_MSG && \\
+
+echo Login password -- "\$display_passwd" >\$LOGIN_MSG && \\
+echo \$notification >> \$LOGIN_MSG && \\
+chmod 600 \$LOGIN_MSG && \\
+/usr/sbin/usermod -p "\$cryptpasswd" root && \\
+if id serengeti >/dev/null 2>&1; then /usr/sbin/usermod -p "\$cryptpasswd" serengeti; fi
+EOP
+) > <%= usr_sbin_path %>/serengeti-password
+chmod 775 <%= usr_sbin_path %>/serengeti-password
+
+(
+cat <<'EOP'
+#!/bin/bash
+
+tty=\`eval echo \\\\\\$\\\${#}\` # Last argument
+
+exec </dev/\$tty >/dev/\$tty 2>&1
+
+stty -echo
+clear
+
+MSG_FILE=<%= usr_sbin_path %>/login_msg
+if [ -f \$MSG_FILE ]; then
+  cat \$MSG_FILE
+fi
+
+while read c; do
+  exec /sbin/mingetty --noclear  "\$@"
+done
+EOP
+) > <%= usr_sbin_path %>/serengeti-tty
+chmod 775 <%= usr_sbin_path %>/serengeti-tty
+
+# We show an serengeti welcome screen instead of login prompt on tty1.
+# tty[2-6] are disabled.
+sed -i "s|^\(1:.*\):/sbin/mingetty|\1:<%= usr_sbin_path %>/serengeti-tty|" /etc/inittab
+sed -i "s|^\([2-6]:.*/sbin/mingetty\)|#\1|" /etc/inittab
+
+/sbin/init q
+
+if [ ! -f <%= usr_sbin_path %>/.serengeti-password.log ]; then
+  <%= usr_sbin_path %>/serengeti-password -a > <%= usr_sbin_path %>/.serengeti-password.log
+fi
+
+<%- end %>
+
 # generate /etc/chef/client.pem
 <%- if @config[:client_key] %>
 (
